project:
  type: book
  output-dir: ../docs
  pre-render: cp -r ../figures ./figures
  post-render: rm -r ./figures

book:
  title: "Exploration of Sea Pens Data"
  author: "Vincent Bellavance"
  date: "2023-03-16"
  sidebar:
    search: false
    title: Sections
    pinned: true
  chapters:
    - index.qmd
    - sea_pens_occurrence_data.qmd
    - part: environmental_variables.qmd
      chapters:
      - bathymetry.qmd
      - oxygen.qmd
      - salinity.qmd
      - temperature.qmd
      - current_velocity.qmd
      - chloro_phyto.qmd
      - molecules_elements.qmd
      - sediments.qmd
      - surf_ice_cover.qmd
      - surf_pp.qmd
      - surf_calcite.qmd
    - part: species_distribution_modelling.qmd
      chapters:
        - models.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false

fig-cap-location: margin

