project:
  type: book
  output-dir: ../docs
  pre-render: cp -r ../figures ./figures
  post-render: rm -r ./figures

book:
  title: "Identification des habitats potentiels des plumes de mer dans l’estuaire maritime et le golfe du Saint-Laurent"
  author: 
    - "Vincent Bellavance"
    - "Cindy Grant"
    - "Philippe Archambault"
  date: "2023-03-17"
  sidebar:
    search: false
    title: Sections
    pinned: true
  chapters:
    - index.qmd
    - summary.qmd
    - sea_pens_occurrence_data.qmd
    - part: environmental_variables.qmd
      chapters:
        - fond_marin.qmd
        - surface.qmd
    - part: species_distribution_modelling.qmd
      chapters:
        - models.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
#  pdf:
#    fig-pos: 'h'

fig-cap-location: margin

