# Résumé

Ce rapport a pour but de documenter l'avancement sur le projet d'identification des habitats potentiels des plumes de mer dans l'estuaire maritime et le golfe du Saint-Laurent.
Il se décline en trois parties:

* [Les données d'occurrence des plumes de mer](sea_pens_occurrence_data.qmd)
  
  + Sources des données
  + Traitement des données
  + Cartes des occurrences de chaque espèce


* [Les variables environnementales à considérer pour les modèles](environmental_variables.qmd)

  + Liste d'articles sur la distribution des plumes de mer avec la liste de variables environnementales associées à sa présence.
  + Liste des données à considérer pour la modélisation des habitats potentiels des plumes de mer dans l'estuaire maritime et le golfe du Saint-Laurent.


* [Choix des modèles qui serviront à identifier les habitats potentiels des plumes de mer](species_distribution_modelling.qmd)

  + Modèles choisis pour les données d'occurrences et de biomasse
  + Outil utilisé pour construire les modèles.